### ISSUE TITLE
Update actions to not rely on save-state

### ISSUE THREAD

**Issue by glektarssza** [yao-pkg/pkg-fetch#13]
### Context ###

nice, it seems you should update some actions which will otherwise fail in near future 

```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

it's the docker build and push action.

_Originally posted by @viceice in https://github.com/yao-pkg/pkg-fetch/issues/9#issuecomment-1839345495_

**Comment by robertsLando** [comment]
Agree, also some actions versions could be bumped to latest

**Comment by viceice** [comment]
As a renovate maintainer i would suggest to configure renovate[^1] for this 😅 

[^1]: https://github.com/apps/renovate

**Comment by robertsLando** [comment]
@viceice Would you mind to draft a PR for that? I know renovate bot but never used it yet on my projects

**Comment by viceice** [comment]
You can simply enable the app on this repo, renovate will open an onboarding pr with default renovate config and tell you in the pr descrion what it would do. we can fine-tune that config and renovate will start working when this PR get's merged.

you can make any changes to th PR and tick the rebase checkbox to let renovate update the description.

**Comment by glektarssza** [comment]
I'll probably do the version updates/Renovate bot as a separate PR/issue if that's okay.
