### ISSUE TITLE
Would you consider x86 support for Windows

### ISSUE THREAD

**Issue by Infern1** [yao-pkg/pkg-fetch#16]
I know the previous maintainer didn't want to support x86 on the windows platform, however it works as expected see:

https://github.com/Infern1/pkg-fetch 

We need the x86 version for now since our codebase is not fully 64bit. Need to migrate lot of C and C++ code.

**Comment by robertsLando** [comment]
Instead of supporting it here directly I suggest you to submit a PR to https://github.com/yao-pkg/pkg-binaries. I can add it there
