### ISSUE TITLE
Build node v20.11.0 binaries

### ISSUE THREAD

**Issue by viceice** [yao-pkg/pkg-fetch#17]
Node v20.11.0 was released on 2024-01-09[^1], so please provide newer builds. 🤗 

[^1]: [@yao-pkg/pkg](https://nodejs.org/en/blog/release/v20.11.0)

**Comment by robertsLando** [comment]
https://github.com/yao-pkg/pkg-fetch/pull/18

**Comment by robertsLando** [comment]
https://github.com/yao-pkg/pkg/releases/tag/v5.11.2

**Comment by viceice** [comment]
- https://github.com/containerbase/base/pull/2148

need to fix my patch manually tomorrow

**Comment by viceice** [comment]
- https://github.com/containerbase/base/actions/runs/7815654958/job/21319472939#step:7:67

It's using node v20.11.0 🎉
