### ISSUE TITLE
Update Node.js versions and binaries for Feb 14 security releases

### ISSUE THREAD

**Issue by jcoglan** [yao-pkg/pkg-fetch#27]
Node.js [just announced new releases of v18, v20 and v21](https://nodejs.org/en/blog/vulnerability/february-2024-security-releases) to address a number of security vulnerabilities. They are patched in v18.19.1, v20.11.1, and v21.6.2.

It looks as though this fork has been keeping up to date with new releases -- thank you very much :) -- so I'm just opening this issue to check if/when these security patches will make it into the `pkg` binaries so we can ship new builds with them.

**Comment by robertsLando** [comment]
#28 #29

**Comment by janl** [comment]
no rush or anything, but what’s the expected turnaround time on the binary build? We know it takes quite a while to build all this from scratch.

Also, are you looking for help with all this, and how can we best help you?

**Comment by viceice** [comment]
builds are stuck pending, they probably needs manual intervention

**Comment by robertsLando** [comment]
https://github.com/yao-pkg/pkg-fetch/actions/runs/7928279506

**Comment by robertsLando** [comment]
https://github.com/yao-pkg/pkg/releases/tag/v5.11.4
