### ISSUE TITLE
Node 18.20.1 security release

### ISSUE THREAD

**Issue by sean-stage** [yao-pkg/pkg-fetch#31]
Node.js [just announced the release of 18.20.1](https://nodejs.org/en/blog/release/v18.20.1) security release. 

This fork seems to be the most active from the original pkg, and has been keeping up with releases. It'll be great if we could get support for 18.20.1 for all main platforms. 

Thank you!

**Comment by robertsLando** [comment]
I have prepared the patch for 20.12 for now: https://github.com/yao-pkg/pkg-fetch/pull/32

**Comment by igorzablotny** [comment]
Hi, is it still planned for the future or should the aforementioned node 20.12.1 release be treated as the only way to include those security patches? The newest version of pkg (5.11.5) uses 18.19.1 version of node.

**Comment by robertsLando** [comment]
Reports said that last patch isn't working and I have no time right now to debug the issue, if someone is able to do that and want to help feel free to submit a PR

**Comment by robertsLando** [comment]
Can someone give a try to #35 ?
