### ISSUE TITLE
[Feature Request] Add Node 22

### ISSUE THREAD

**Issue by Niek** [yao-pkg/pkg-fetch#33]
Now that Node 22 has been released and will be LTS later this year, it would be nice to have support for it in `pkg`.

**Comment by robertsLando** [comment]
Need someone able to do the patch for it, also seems the actual nodejs 20 patches are broken but I have no idea how to fix them

**Comment by faulpeltz** [comment]
I will have a look - but there are a lot of changes in Node 22 vs 20 and also in the V8 versions

**Comment by faulpeltz** [comment]
I opened a PR  #45 with an experimental patch, feel free to try ;)
