### ISSUE TITLE
Binary size

### ISSUE THREAD

**Issue by Mikescops** [yao-pkg/pkg-fetch#36]
Hello,

I was looking at the different binary size and I can't figure out why between 2 node version or 2 arch there is such a big size difference (10mb). 
Is there some optimization put in place? Is it even possible to optimize anything here?

**Comment by robertsLando** [comment]
That's a known thing, seems nodejs versions are bigger on every major, you can try to add compression to optimize it

**Comment by Mikescops** [comment]
Yes I added compression from pkg but my final builds are never going under the 50mb, it's not a big deal I would say nowadays but I was looking to understand more on how it works.

Do you think there could be a way to make slim versions of node by excluding some uneeded parts of it, I imagine that it's a full featured node build but let's say (it's a crazy idea i know) you don't need access to the native `crypto` module, could it be removed from the final build?

**Comment by robertsLando** [comment]
@Mikescops I also use esbuild to create a super slim bundle, check https://github.com/zwave-js/zwave-js-ui/blob/master/esbuild.js

**Comment by Mikescops** [comment]
I know and I took inspiration from your nice work there, my esbuild outputs something like 1.3mb but after pkg i get 53mb and that's mostly because the nodejs binary something like 50mb itself.

**Comment by Mikescops** [comment]
Ok let's close this one.
