### ISSUE TITLE
[Bug / Feture request] Allow spawn to run executables included as assets.

### ISSUE THREAD

**Issue by CodeRunsTheWorld** [yao-pkg/pkg-fetch#39]
I included rar.exe in my 'assets' dir and defined it package.json using

```
"pkg": {
    "assets": "assets/**/*"
},
```

Accessing /assets/rar.exe works fine as a read stream, however spawn fails:

```
Error: spawn C:\snapshot\nodeProjects\logUtils\assets\rar.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\snapshot\\nodeProjects\\logUtils\\assets\\rar.exe',
  path: 'C:\\snapshot\\nodeProjects\\logUtils\\assets\\rar.exe',
  spawnargs: [ 'A', '-S', 'error.2024-07-26.log.rar', 'error.2024-07-26.log' ]
}
```

I can work around this by writing rar.exe to disk first, but it would be really nice if spawn would just work on the snapshot dir.
I'm on windows, not sure if this is also the case on other platforms.

**Comment by robertsLando** [comment]
> I can work around this by writing rar.exe to disk first, but it would be really nice if spawn would just work on the snapshot dir.

Unfortuinately this is not possible, we have to do the same with `.node` native addons as them cannot be loaded as buffers

**Comment by CodeRunsTheWorld** [comment]
Thank you for the clarification / your reply.
