### ISSUE TITLE
Regarding macos-arm64

### ISSUE THREAD

**Issue by CMCDragonkai** [yao-pkg/pkg-fetch#5]
Hi, I was wondering what was the reason why no precompiled version of macos-arm64?

Is it due to code-signing? If so, how should we be building this version so we can integrate it into our pkg pipeline?

**Comment by robertsLando** [comment]
Reason is there is no available github actions runner to build them. Anyway if you find a way feel free to open a PR

**Comment by CMCDragonkai** [comment]
Gitlab has arm64 ci machines. Could be done there.

**Comment by robertsLando** [comment]
@CMCDragonkai PR?

**Comment by CMCDragonkai** [comment]
Are you happy to use gitlab CI?

**Comment by robertsLando** [comment]
There is not problem for me, IMO what we could do is to have a dummy repo on gitlab with a CI that is triggerd by a workflow in this repo, once the gitlab CI ends the workflow downloads the built binary and provides it to the next steps like we do in our `build-<os>.yml` workflows

**Comment by segevfiner** [comment]
Isn't it possible to cross compile node from the Intel macOS runner?

**Comment by robertsLando** [comment]
@segevfiner Would you like to submit a PR?

**Comment by segevfiner** [comment]
> @segevfiner Would you like to submit a PR?

https://github.com/yao-pkg/pkg-fetch/pull/8
