### ISSUE TITLE
Bitdefender detects Trojan.Agent.GMVX in node-v20.17.0-win-x64

### ISSUE THREAD

**Issue by epessoa-i** [yao-pkg/pkg-fetch#52]
Dear maintainers, thanks for your hard work.

Bitdefender detects node-v20.17.0-win-x64 as Trojan.Agent.GMVX.

The VirusTotal report shows other 9 vendors reporting the same https://www.virustotal.com/#/search/9c15a64b3babd2e7cd6c0cb1770495c331bea6df4544df92f734a23cc55bc1bf

Why is this happening?

**Comment by robertsLando** [comment]
@epessoa-i Does they behave the same with old patches? I didn't changed anything in latest patches that could explain this, consider that it's not a news that anti virus detect patches as possible trojan as it's actually an official nodejs build with some changes in source code so if it does some kind of sha check with the official node he will find that's not the same so could detect it to be a trojan and makes sense

**Comment by epessoa-i** [comment]
Hi Daniel, thanks for your response.
They do not behave the same; the previous versions have never been reported as trojans.
The fact is that this version does not always trigger an alarm. When this binary is submitted for sandbox analysis, Bitdefender is able to detect that it attempts to access 192.168.0.10, which raises an issue.

**Comment by robertsLando** [comment]
> When this binary is submitted for sandbox analysis, Bitdefender is able to detect that it attempts to access 192.168.0.10, which raises an issue.

Are you speaking about the binary downloaded or the binary produced by pkg? If the latter the problem could be the code you are using.

All binaries are builder using github actions by just cloning nodejs repo, apply the [patch](https://github.com/yao-pkg/pkg-fetch/tree/main/patches) and then build nodejs. Once done the binary is uploaded to Github releases with also a sha so everything can be traked safely, see https://github.com/yao-pkg/pkg-fetch#security.

This to say that there is nothing I can have done to cause that issue with your antivirus here

**Comment by epessoa-i** [comment]
I'm refering to the file node-v20.17.0-win-x64.

Report screenshots:
![image](https://github.com/user-attachments/assets/7409062d-c126-4b31-8062-508d652f3c0c)
![image](https://github.com/user-attachments/assets/38796449-84df-443f-93b0-a2030d47edbb)
TCP 40.83.240.146 -> 192.168.0.10:49687
Sent: 11 packet(s) - 4.84 KB
Received: 10 packet(s) - 2.25 KB
At the same time, Bitdefender describes the traffic as clean.

Your assumption may be correct; the antivirus provider might have raised suspicion upon identifying that it was a modified version of node.
