### ISSUE TITLE
Consider x86 for Windows

### ISSUE THREAD

**Issue by Infern1** [yao-pkg/pkg-fetch#60]
Hi All,

I can easily build the x86 version of pkg-fetch, see: https://github.com/Infern1/pkg-fetch/actions

Would be helpfull if this can be done by default.

I know x86 has been dropped, however we cannot switch 64bit since our C++ application for which we have a .node file is not 64bit. This takes some time.

**Comment by robertsLando** [comment]
While I understand it works for you now based on my experience it is a pain to keep it maintained. Every time nodejs releases a new minor release something breaks on builds, last time it took me weeks to fix them all so I prefer to keep maintained only the most used ones. Hope you understand 🙏🏼
