### ISSUE TITLE
Add Node 20

### ISSUE THREAD

**Issue by segevfiner** [yao-pkg/pkg-fetch#9]
It's now the latest LTS.

**Comment by robertsLando** [comment]
Unfortunately we don't have anyone right now able to create the v20 patches

**Comment by glektarssza** [comment]
Would be addressed by #11

**Comment by robertsLando** [comment]
Fixed in #11

**Comment by robertsLando** [comment]
I tried a fix in #12 see https://github.com/yao-pkg/pkg-fetch/actions/runs/7087432653/job/19287673723

**Comment by viceice** [comment]
nice, it seems you should update some actions which will otherwise fail in near future

**Comment by glektarssza** [comment]
> nice, it seems you should update some actions which will otherwise fail in near future
> 
> ```
> Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> ```
> 
> it's the docker build and push action.

@viceice I can open a separate ticket and take a look at this in the next few days if you want.

**Comment by viceice** [comment]
> > nice, it seems you should update some actions which will otherwise fail in near future
> > 
> > ```
> > Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> > ```
> > 
> > it's the docker build and push action.
> 
> @viceice I can open a separate ticket and take a look at this in the next few days if you want.

I would suggest to use renovate for automated updates (I'm a maintainer 😉)

**Comment by glektarssza** [comment]
> > > nice, it seems you should update some actions which will otherwise fail in near future
> > > ```
> > > Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > it's the docker build and push action.
> > 
> > 
> > @viceice I can open a separate ticket and take a look at this in the next few days if you want.
> 
> I would suggest to use renovate for automated updates (I'm a maintainer 😉)

@viceice Sure, I can look at it! I'll open an issue to track.

**Comment by robertsLando** [comment]
Seems some matrix was missing :( need to trigger another build

https://github.com/yao-pkg/pkg-fetch/commit/28d96e99af719107d3ee4211d987a6f0e8dd9800

**Comment by robertsLando** [comment]
will remove nodejs19 on next release, just because we need to be sure v20 works propely before dropping it. Every feedback is welcome!

**Comment by viceice** [comment]
Will try v20 at https://github.com/containerbase/base now

**Comment by viceice** [comment]
@robertsLando Can you publish a new release of `@yao-pkg/pkg-fetch` and `@yao-pkg/pkg` to include the v20?

```
Error [ReportedError]: No available node version satisfies 'v20'
```

🙃

**Comment by robertsLando** [comment]
@viceice Actually I'm waiting for this to end: https://github.com/yao-pkg/pkg-fetch/actions/runs/7097555049

linux-arm64 and macos arm64 binaries were missing.

Anyway I suggest you to clone both packages locally and use npm link

**Comment by robertsLando** [comment]
pkg 5.11.0 is out now

**Comment by viceice** [comment]
will try tomorrow

**Comment by glektarssza** [comment]
> Seems some matrix was missing :( need to trigger another build
> 
> [28d96e9](https://github.com/yao-pkg/pkg-fetch/commit/28d96e99af719107d3ee4211d987a6f0e8dd9800)
> 
> Closing this

How on earth did I miss that... :<

Oh well, glad you caught it.

**Comment by robertsLando** [comment]
No worries @glektarssza you already did a lot with that patch 🙏🏻

**Comment by viceice** [comment]
Seems to work for amd64 and arm64 🎉 
- https://github.com/containerbase/base/pull/1834

**Comment by robertsLando** [comment]
Just created a workflow that automatically bumps patches (at least when them apply cleanly) 🚀
